name: "Exemplo pipeline"

on:
  workflow_dispatch:

jobs:
  estagio1:
    runs-on: ubuntu-latest
    steps:
      - name: "Olá Mundo"
        run: echo "Olá GitHub Actions!"
      - name: Sleep
        run: Sleep 1
      - name: "Outro Echo"
        run: echo "Echo qualquer coisa"

  estagio2:
    needs: estagio1
    runs-on: ubuntu-latest
    steps:
      - name: "Sleep"
        run: echo "Sleep 5"

  estagio3:
    needs: estagio2
    runs-on: ubuntu-latest
    steps:
      - name: "Sleep"
        run: echo "Sleep 2"