name: "Exemplo pipeline"

on:
  workflow_dispatch:
  push: [main]

jobs:
  integração-contínua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Listagem de conteúdo do diretório
        run: ls -la
      - name: Outro Echo
        run: echo "Echo qualquer coisa"

  estagio2:
    needs: estagio1
    runs-on: ubuntu-latest
    steps:
      - name: "Sleep"
        run: echo "Sleep 5"

  estagio3:
    needs: estagio2
    runs-on: ubuntu-latest
    steps:
      - name: "Sleep"
        run: echo "Sleep 2"